### PR TITLE
implement dynamic language querying

### LINKED ISSUE #1: Dynamically query all languages on github
Currently, language-guesser is limited to only showing a few hard-coded languages, but it should be possibly to use all languages on github. All the languages github knows are kept in [this yaml file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml), so we should be able to query it, and then deserialize it. Note that languages with spaces in their names aren't a problem, if the query is delimeted with quotes, for example `language:"language with spaces"`.

I'm interested in contributing :D

### PR DESCRIPTION
**Pull request by LordMZTE**
closes #1

### CODE REVIEW

**Comment by ModProg** [comment]
I'll have a look in the evening

**Comment by ModProg** [comment]
Is there some way to get the most used languages so that we can add an option limiting the languages? Because this game is now quite impossible, often times :D 

Or just add an option where you can provide the possible languages.

**Comment by LordMZTE** [comment]
I don't know how I would find out the most used languages. Even if we did that, it'd probably just be a bunch of JS and python anyways.

How should I implement the option for the possible languages? As CLI params?

**Comment by ModProg** [comment]
> How should I implement the option for the possible languages? As CLI params?
yeah, I would say something like

```
--languages rust go ruby java typescript python latex
```

**Comment by ModProg** [comment]
Maybe I'll manually create a flag to get some specific sets of languages, but for now that would be the most general solution.

**Pull request merged**
